### ISSUE TITLE
Add agent characteristics to nodes

### ISSUE THREAD

**Issue by terryneumann** [ridicholas/fairness_in_fact_checked_info_ecosystem#5]
Use ```create_polarized_network``` as a guide to append relevant data to nodes.

**Comment by terryneumann** [comment]
Specifically this segment of code:

```
for node, data in G.nodes(data=True):
        data['lambda'] = np.random.uniform(0.001,0.75)
        data['wake'] = 0 + np.round(np.random.exponential(scale = 1 / data['lambda']))
        data['inbox'] = []
        data['mentioned_by'] = []


        if node < size:
            data['belief'] = np.random.uniform(0,0.5)
        else:
            data['belief'] = np.random.uniform(0.5,1.0)
        if data['belief'] < 0.2:
            data['kind'] = 'beacon'
        else:
            data['kind'] = 'normal'



    num_bots = int(np.round(len(G.nodes)*perc_bots))
    bot_names = [len(G) + i for i in range(num_bots)]
    for bot_name in bot_names:
        initial_links = random.sample(G.nodes, bot_initial_links)
        G.add_node(bot_name)
        for link in initial_links:
            G.add_edge(bot_name,link)
    
# Add Bot Data      
    for node, data in G.nodes(data=True):
        if node in bot_names:
            '''
            Bots have a much higher inter-arival time
            '''
            data['lambda'] = np.random.uniform(0.1,0.75)
            data['wake'] = 0 + np.round(np.random.exponential(scale = 1 / data['lambda']))
            data['inbox'] = []
            data['belief'] = np.random.uniform(0.95,1.0)
            data['kind'] = 'bot'
            data['mentioned_by'] = []

```

**Comment by ridicholas** [comment]
making this step 2. 

update 'belief' to a topic dictionary so nodes have a 'belief' for every topic (numTopics provided as param). Maybe change belief to 'sentiment'? 
add 'impactedness' dictionary to each node so nodes have 'impactedness' for every topic. 

note to discuss in person. do we create hard coded belief/impactedness per community generation (like how belief is generated in the original code) or have this be something that is passed in to function to allow for us to run different simulations. This is just a implementation decision that wont make any difference on our experiments because we have two equivalent options (i think). We can keep node belief/impactedness 'static' while allowing for variations in information generation. or we can allow for variations in belief/impactedness variation while keeping information generation 'static'.

**Comment by ridicholas** [comment]
'taken care of' with latest push
